// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieF4f51xWHVP_Wl8afzm3TWhutcqNLmo',
    appId: '1:87292615185:web:b0a37a73eb64812879afb0',
    messagingSenderId: '87292615185',
    projectId: 'todoapp-b3eca',
    authDomain: 'todoapp-b3eca.firebaseapp.com',
    storageBucket: 'todoapp-b3eca.appspot.com',
    measurementId: 'G-XXTYBMQ35Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY8BKbGmyJzuYgV93ZpfC99i9NjW28je8',
    appId: '1:87292615185:android:cbe2eb9f03ba673d79afb0',
    messagingSenderId: '87292615185',
    projectId: 'todoapp-b3eca',
    storageBucket: 'todoapp-b3eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLiTNK2_LHhhvbOfbfVfHc4lxj3BhZ2rc',
    appId: '1:87292615185:ios:f94b21aea1966b6e79afb0',
    messagingSenderId: '87292615185',
    projectId: 'todoapp-b3eca',
    storageBucket: 'todoapp-b3eca.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLiTNK2_LHhhvbOfbfVfHc4lxj3BhZ2rc',
    appId: '1:87292615185:ios:30b0a3b74ae945f779afb0',
    messagingSenderId: '87292615185',
    projectId: 'todoapp-b3eca',
    storageBucket: 'todoapp-b3eca.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
